import os
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import HttpResponseBadRequest
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
import datetime
from django.utils import timezone
from .models import User

# Define the scopes we need
SCOPES = [
    'https://www.googleapis.com/auth/gmail.readonly',
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'openid'
]

def get_google_flow(request):
    client_config = {
        "web": {
            "client_id": settings.GOOGLE_OAUTH_CLIENT_ID,
            "project_id": "smart-mail-analyzer",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_secret": settings.GOOGLE_OAUTH_CLIENT_SECRET
        }
    }
    
    # In development, HTTP is fine. In production, this should be HTTPS.
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

    flow = Flow.from_client_config(
        client_config,
        scopes=SCOPES,
    )
    
    # Use the accounts:google_callback URL
    flow.redirect_uri = request.build_absolute_uri(reverse('accounts:google_callback'))
    return flow

def login_view(request):
    if request.user.is_authenticated:
        return redirect('chat:index')
    return render(request, 'accounts/login.html')

def google_login(request):
    flow = get_google_flow(request)
    authorization_url, state = flow.authorization_url(
        access_type='offline',
        prompt='consent' # Force consent to get a refresh token
    )
    request.session['state'] = state
    # Save the PKCE code_verifier generated by the flow in the session
    request.session['code_verifier'] = getattr(flow, 'code_verifier', None)
    return redirect(authorization_url)

def google_callback(request):
    state = request.session.get('state')
    if not state or state != request.GET.get('state'):
        return HttpResponseBadRequest("Invalid state parameter. Please try logging in again.")

    flow = get_google_flow(request)
    # Restore the PKCE code_verifier from the session
    code_verifier = request.session.get('code_verifier')
    if code_verifier:
        flow.code_verifier = code_verifier

    try:
        # Fetch tokens
        flow.fetch_token(authorization_response=request.build_absolute_uri())
    except Exception as e:
        return HttpResponseBadRequest(f"Failed to fetch token: {str(e)}")

    credentials = flow.credentials
    
    # Get user email
    try:
        user_info_service = build('oauth2', 'v2', credentials=credentials)
        user_info = user_info_service.userinfo().get().execute()
        email = user_info.get('email')
    except Exception as e:
        return HttpResponseBadRequest(f"Failed to get user info: {str(e)}")

    if not email:
        return HttpResponseBadRequest("Google did not provide an email address.")

    # Create or update user
    user, created = User.objects.get_or_create(email=email)
    
    # AbstractUser requires username
    if created:
        user.username = email.split('@')[0] + '_' + str(user.pk or '0')
    
    user.google_access_token = credentials.token
    user.google_refresh_token = credentials.refresh_token or user.google_refresh_token
    
    if credentials.expiry:
        # credentials.expiry is a datetime object in UTC
        if credentials.expiry.tzinfo is None:
            user.google_token_expiry = credentials.expiry.replace(tzinfo=datetime.timezone.utc)
        else:
            user.google_token_expiry = credentials.expiry

    user.save()

    # Log the user in
    login(request, user)
    
    # Clean up state
    if 'state' in request.session:
        del request.session['state']

    return redirect('chat:index')

def logout_view(request):
    logout(request)
    return redirect('accounts:login')
